[package]
name = "pump"
version = "1.0.0"
authors = []

[addresses]
pump="0x12a655b83d3c28d36a2c52ccd8cdcc15df50c100f1fd34de038755b7adacc4b6"
pump_admin="0x12a655b83d3c28d36a2c52ccd8cdcc15df50c100f1fd34de038755b7adacc4b6"


[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "dev"
subdir = "aptos-move/framework/supra-framework"

[dependencies.dexlyn_swap]
git = "https://github.com/DexlynLabs/dexlyn_swap_interface"
rev = "testnet"

[dev-dependencies]
